### ISSUE TITLE
python inference.py --eval --dataset val2014_novel --net hanmcl --r --load_dir models/hanmcl --checkepoch 12 --checkpoint 34467 --bs 1 --shot 3 --eval_dir result

### ISSUE THREAD

**Issue by luoyq6** [infinity7428/hANMCL#11]
coco_20_set1
loading annotations into memory...
Done (t=0.20s)
creating index...
index created!
Loaded dataset `coco_set1_20` for training
Set proposal method: gt
Preparing training data...
Traceback (most recent call last):
  File "inference.py", line 34, in <module>
    imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdbval_name, False)
  File "/dfs/data/hANMCL/lib/roi_data_layer/roidb.py", line 121, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/dfs/data/hANMCL/lib/roi_data_layer/roidb.py", line 121, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/dfs/data/hANMCL/lib/roi_data_layer/roidb.py", line 118, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/dfs/data/hANMCL/lib/roi_data_layer/roidb.py", line 107, in get_training_roidb
    prepare_roidb(imdb)
  File "/dfs/data/hANMCL/lib/roi_data_layer/roidb.py", line 27, in prepare_roidb
    roidb[i]['image'] = imdb.image_path_at(i)
  File "/dfs/data/hANMCL/lib/datasets/coco_split.py", line 100, in image_path_at
    return self.image_path_from_index(self._image_index[i])
  File "/dfs/data/hANMCL/lib/datasets/coco_split.py", line 141, in image_path_from_index
    assert osp.exists(image_path), \
AssertionError: Path does not exist: /dfs/data/hANMCL/data/coco/images/val2014/COCO_val2014_000000181666.jpg

**Comment by lxylxq001** [comment]
Try checking your file path

**Comment by infinity7428** [comment]
You can download the validation data here.
https://cocodataset.org/#download
